#!/bin/bash
  
worker_dir=$(cat $PFILE | grep worker_dir | sed 's/=/ /g' | awk '{print $2}')
recursive_count=$(cat $PFILE | grep recursive_count | sed 's/=/ /g' | awk '{print $2}')
recursive_interval=$(cat $PFILE | grep recursive_interval | sed 's/=/ /g' | awk '{print $2}')
workflow_dir=$(cat $PFILE | grep workflow | sed 's/=/ /g' | awk '{print $2}')

if ! test -f $workflow_dir/stage.lst; then
  echo "End refreshing database tables" > $workflow_dir/stage.lst
fi

t=$((0))
while [ $t -eq 0 ]
do
	if [ $(ps -ef | grep c_arrive | grep -v grep | wc -l) -eq 0 ]; then
		if [ "$(cat $workflow_dir/stage.lst)" == "End refreshing database tables" ]; then	
			$worker_dir/c_arrive
		fi;
	fi
	if [ $(ps -ef | grep c_schema | grep -v grep | wc -l) -eq 0 ]; then
                if [ "$(cat $workflow_dir/stage.lst)" == "End checking on Arrive folder" ]; then       
	       		$worker_dir/c_schema
		fi
        fi
	if [ $(ps -ef | grep c_table | grep -v grep | wc -l) -eq 0 ]; then
                if [ "$(cat $workflow_dir/stage.lst)" == "End creating database schema" ]; then
                        $worker_dir/c_table
                fi
        fi
	if [ $(ps -ef | grep c_refresh | grep -v grep | wc -l) -eq 0 ]; then
                if [ "$(cat $workflow_dir/stage.lst)" == "End creating lakehouse table" ]; then
                        $worker_dir/c_refresh
                fi
        fi
        sleep $recursive_interval
        if [ $(ps -ef | grep c_instance | grep -v grep | wc -l) -eq 0 ]; then
                t=$((1))
        fi;
done
