#!/bin/bash

username=$(cat $PFILE | grep username | sed 's/=/ /g' | awk '{print $2}')
password=$(cat $PFILE | grep password | sed 's/=/ /g' | awk '{print $2}')
server=$(cat $PFILE | grep server | sed 's/=/ /g' | awk '{print $2}')
port=$(cat $PFILE | grep port | sed 's/=/ /g' | awk '{print $2}')
mount_point=$(cat $PFILE | grep mount_point | sed 's/=/ /g' | awk '{print $2}')
workflow_dir=$(cat $PFILE | grep workflow | sed 's/=/ /g' | awk '{print $2}')

echo "Start creating database schema" > $workflow_dir/stage.lst

cp $workflow_dir/new_db.lst $workflow_dir/new_db.temp
cp $workflow_dir/refresh_db.lst $workflow_dir/refresh_db.temp

cat $workflow_dir/new_db.temp | awk '{print "create database if not exists "$1";"}' > $workflow_dir/create_db.sql
cat $workflow_dir/refresh_db.temp | awk '{print "create database if not exists "$1";"}' >> $workflow_dir/create_db.sql

mysqlsh -u$username -p$password -h$server -P$port --sqlc -e "source $workflow_dir/create_db.sql"

echo "End creating database schema" > $workflow_dir/stage.lst

for dbname in $(cat $workflow_dir/new_db.temp); do
	sed -i "/$dbname/d" $workflow_dir/new_db.lst	
done;
